image: node:8-alpine

stages:
  - tests
  - publish

before_script:
  - echo $NPMRC_REGISTRY_KEY > $CI_PROJECT_DIR/.npmrc
  - yarn

tests:
  stage: tests
  script:
    - yarn run test
  tags:
    - PMD
    - STG
    - ci

publish:
  stage: publish
  only:
    - tags
  script:
    - yarn run build
    - npm version --no-git-tag-version ${CI_COMMIT_TAG}
    - npm publish
  tags:
    - PMD
    - STG
    - ci
